### PR TITLE
Move phase plane from intro

### PR DESCRIPTION
**Pull request by rjleveque**
Now point to the separate html file so this looks better in the pdf file, addresses #79.

### CODE REVIEW

**Comment by ketch** [comment]
Thanks!  It would be nice if the PDF hyperlink also worked, but we would want a full URL link for that.  Maybe we can point to the gh-pages copy?

**Comment by rjleveque** [comment]
@ketch: The link to the phase plane should work once #83 is merged.

**Comment by rjleveque** [comment]
I haven't tested this in the pdf yet since `bookbook` stopped working for me...

**Comment by ketch** [comment]
I'm not sure why this still shows as open after I merged #83.  There must be some additional commits here?

**Comment by rjleveque** [comment]
Yes, this is distinct from #83 -- this modifies two notebooks to point to the webpage.

**Comment by rjleveque** [comment]
Oops, I take back my previous comment.  What's different is that this PR merges into `master` while #83 merged into `gh-pages`.  

Going forward we need to remember to merge `master` into `gh-pages` before updating the html files for webpages.

**Pull request merged**
