### PR TITLE
Implement changes suggested by Mauricio.

### PR DESCRIPTION
**Pull request by ketch**
See #200.

### CODE REVIEW

**Comment by rjleveque** [comment]
I think in `Approximate_solvers` we need to replace `\wave` with `{\matcal W}` and `\apdq` with `{\cal A}^+` since the macros aren't found (are they supposed to be)?  Elsewhere these are written out explicitly.

I don't know what's going on with travis, but the tests seem to pass.

**Comment by ketch** [comment]
>I think in Approximate_solvers we need to replace \wave with {\matcal W} and \apdq with {\cal A}^+ since the macros aren't found (are they supposed to be)? Elsewhere these are written out explicitly.

I made this work earlier with a plugin, but it's not worth it at this point.  So I made these changes, except I used \cal because \mathcal didn't work.

**Comment by rjleveque** [comment]
Grepping `mathcal` it seems to be used in other notebooks such as `Shallow_water_approximate` and seems to work fine.  (But note I misspelled it in my comment above, so if you copied and pasted, `matcal` wouldn't work.)

But the resulting rendered version seems to be the same with either one, so I don't think it matters.

**Comment by ketch** [comment]
> if you copied and pasted

LOL, yes, I did exactly that.  Must not have been thinking too clearly at the time...

**Pull request merged**
