### PR TITLE
Add test script, requirements, and travis script.

### PR DESCRIPTION
**Pull request by ketch**
The test script simply executes each notebook.

### CODE REVIEW

**Comment by ketch** [comment]
This tests all notebooks using both Python 2 and Python 3.  Right now the tests fail because of #32.  I'm planning to merge this anyway, but we should fix #32 ASAP and then avoid merging anything that breaks the tests.

I also added installation instructions to the README, which should give a user all the dependencies.  Anyone can run the tests via

    python test.py

Note that we don't actually check that the output is correct; we only check that no exceptions are raised.

**Comment by ketch** [comment]
By the way, I stole the code for testing from http://blog.thedataincubator.com/2016/06/testing-jupyter-notebooks/.  I had to modify it to make it work with Python 2 and 3.

**Comment by ketch** [comment]
I'm going to make this work with nosetests and make it run the doctests.

**Comment by ketch** [comment]
Okay, now nosetests will pick this up.  You should run it with

    nosetests --with-doctest

to run the doctests too.  Also,

   python test.py

still works fine.

This is ready to merge.

**Comment by rjleveque** [comment]
It passes also on the Tamman notebook after I merged in #35 on my laptop.

**Pull request merged**
