### PR TITLE
Burgers/traffic swap

### PR DESCRIPTION
**Pull request by rjleveque**
I talked to @ketch yesterday about possibly swapping the order of these two notebooks to put `Burgers` before `Traffic_flow` since I find it more natural to teach them in this order.  This PR has some modifications to both to make them flow better in this order as a possible revision.  I don't think David is convinced this is a good idea, so this is still open to discussion!

I fixed a few other things, but there is an interact in `Burgers` that is still broken, as discussed in #178.  I tried fiddling with this, and there does seem to be an uncaught exception in the last part of `burgers.riemann_solution_interact`.  But I didn't write this gui code and don't really understand how these more complex widgets are supposed to be working. As far as I can see what's done here is identical to what's done in the some of the acoustics widgets that work fine.  So maybe whoever wrote this code (@maojrs ?) can figure out what's going wrong?

### CODE REVIEW

**Comment by maojrs** [comment]
The interact in Burgers is fine. It just the import statment within burgers.py or burgers_demo.py. I opened an issue a while ago since there were some modifications to Burgers’ notebook that were not neccesary. I opened an issue #185 to discuss them with you.

Regarding te order, it is the same for me. I personally find burgers an easier first equation, and I find it more intuitive, but I might be bias since I have worked a lot with it. 

I am currently on holidays until the 25, but I am happy to do any necessary updates to Burgers when I get back.

**Comment by ketch** [comment]
This looks good and I agree that it's a good idea.

I notice that you added extra blank lines around some equations.  This improves the appearance in the notebook, but adds a paragraph break in the PDF.  I haven't found a solution to this problem.

**Comment by rjleveque** [comment]
Thanks @maojrs, I knew I'd seen something from you about what the problem was but couldn't find it.  I fixed it and closed #185.  

I also put this interact in a separate section and started a new section to discuss the animations that follow, perhaps clearer especially in the pdf that doesn't have the interact.  I considered putting the `hide` tag on the cell with this interact, but decided to leave it in the pdf even though it doesn't show anything interesting.  What do you think?

@ketch: I removed most of the blank lines around displayed equations, I forgot about that issue.

**Comment by maojrs** [comment]
@rjleveque I like the new order. Regarding the interact of the full solution, I also think it is only interesting because of the interactivity. However, it is also ok to leave it in the pdf, so readers become curious to try the online version. I could go either way, but I think keeping it in the pdf would be better.

I also noticed you added a "fig" input parameter to `burgers_demo/multivalued_solution` and `burgers_demo/shock_location`. From my point of view this extra parameter is not necessary, but maybe you added it for a specific reason?

**Comment by rjleveque** [comment]
I added `fig` as a parameter in many demos at one time so that it would keep using the same figure and not produce a long sequence of plots in the notebook when making an animation.  But maybe there's a way to avoid it or it now just works without it.  I can experiment with that some more.

For now I'm going to merge this PR so we can move forward with other things.

**Comment by maojrs** [comment]
I see, I think it should work fine without it since they are simply interacts, like all the other interacts in the notebook that don't have it, but I could be wrong. In any case, it can easily be changed later.

**Comment by rjleveque** [comment]
But some interacts get turned into animations when making the html version, so maybe that's where I had problems...

**Pull request merged**
