### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rjleveque**
Add Contents section copied from Index.ipynb

### CODE REVIEW

**Comment by ketch** [comment]
This seems fine; I find that occasionally Github is slow to render notebooks or even fails.  That mostly happens with large notebooks so probably wouldn't affect the index, but this just potentially makes it easier for some people to access.

**Comment by ketch** [comment]
Now that I merged it I just realized that it doesn't include the hyperlinks -- was that intended?  I think we should include the links; if you agree then I can do that.

**Comment by maojrs** [comment]
I think we should definitely include the links.

**Comment by rjleveque** [comment]
I intentionally didn't include the links because linking to the notebook
has the same problem David mentioned that sometimes they don't load (and
this happened for me even with Index.ipynb the other day).  And if it does
load all they see is the input cells stripped of output, and so not so
useful and potentially confusing to those not familiar with notebooks.

We could instead link to the html versions, but that's potentially
confusing in other ways.  Since there are other links in the README to the
rendered notebooks and instructions on how to open notebooks in a way that
they can execute them, I thought the purpose of putting the index here was
simply so people can more easily see what's in the book without having to
open anything.  But I'm happy to be convinced otherwise.

 - Randy

**Comment by maojrs** [comment]
Ohh I see. In that case I think it is also ok as it is now.

**Comment by ketch** [comment]
What if I change the chapter names in the TOC at the bottom of the README to be the actual notebook file names (in backticks), so it's completely clear which notebook is referred to?

**Comment by rjleveque** [comment]
@ketch - Yes, that sounds like a great solution.

**Comment by ketch** [comment]
Okay, I went ahead and just edited the README directly.

**Comment by rjleveque** [comment]
Looks good, thanks!

**Pull request merged**
